// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200715105414_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("AccountId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(MAX)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(MAX)");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
